---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  token: {{ .Values.secrets.vault.token | b64enc }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vault.server | quote }}
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: database
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: database
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-credentials
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: database
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: database
      property: password