run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - tools

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocritic
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - exitAfterDefer
      - ifElseChain
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - revive
    - path: tools/
      linters:
        - gocritic
        - revive