{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-credentials
  namespace: {{ .Values.global.namespace | default "student-api" }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: database
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: database
      property: password
{{- end }}