enabled: true

global:
  namespace: student-api

image:
  repository: johntoby/stanford-students-api
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2

nodeSelector:
  type: application

service:
  type: ClusterIP
  port: 8080

config:
  dbHost: "postgres-service"
  dbPort: "5432"
  dbName: "stanford_students"
  port: "8080"
  logLevel: "info"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

probes:
  liveness:
    path: /healthcheck
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /healthcheck
    initialDelaySeconds: 5
    periodSeconds: 5