global:
  namespace: student-api

app:
  name: stanford-api
  image:
    repository: johntoby/stanford-students-api
    tag: 72ba28e6fb6260ca6d189fdec1837c07e3d89d30
    pullPolicy: IfNotPresent
  replicas: 5
  port: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  nodeSelector:
    type: application
  config:
    dbHost: postgres-service
    dbPort: "5432"
    dbName: stanford_students
    logLevel: info

database:
  config:
    dbName: stanford_students
  nodeSelector:
    type: database

vault:
  enabled: true
  server:
    dev:
      enabled: true
      devRootToken: "root"
    nodeSelector:
      type: dependent_services
  injector:
    enabled: false

postgresql:
  enabled: false

external-secrets:
  enabled: true
  nodeSelector:
    type: dependent_services

secrets:
  vault:
    server: "http://vault-service.vault-system.svc.cluster.local:8200"
    token: "root"
  database:
    username: postgres
    password: postgres