enabled: true

global:
  namespace: student-api

image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: v0.9.11
  pullPolicy: IfNotPresent

replicas: 1

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

nodeSelector:
  type: dependent_services